In [233]:
#Gauss-Seidel method
#Works for SPD or strictly diagonally dominant matrices

import numpy as np

def GauSeiIT(A,u,f):
    N = np.size(u) 
    u[0] = (f[0] - np.dot(A[0,1:],u[1:]))/A[0,0] #Do first and last steps manually 
    for i in range(1,N-1):
        u[i] = (f[i]-np.dot(A[i,:i-1],u[:i-1])-np.dot(A[i,i+1:],u[i+1:]))/A[i,i] #algorithm
    u[N-1] = (f[N-1]-np.dot(A[N-1,:N-2],u[:N-2]))/A[N-1,N-1] #last step
    return u

def GauSei(A,u,f,n): #Do n steps of Gauss-Seidel
    u0 = u
    for i in range(n):
        #print(u0)
        u0 = GauSeiIT(A,u0,f)
    return u0


In [234]:
#SSOR method

import numpy as np

def SORit(A,u,w,f):
    N = np.size(u)
    s0 = u[0]
    u[0] = (f[0] - np.dot(A[0,1:],u[1:]))/A[0,0]  #First step manually
    u[0] = (1-w)*s0+w*u[0]
    for i in range(1,N-1): #Do N-2 steps automatically following algorithm
        s = u[i]
        u[i] = (f[i]-np.dot(A[i,:i-1],u[:i-1])-np.dot(A[i,i+1:],u[i+1:]))/A[i,i]
        u[i] = (1-w)*s+w*u[i]
    sN = u[N-1] #Do last step manually
    u[N-1] = (f[N-1]-np.dot(A[N-1,:N-2],u[:N-2]))/A[N-1,N-1]
    u[N-1] = (1-w)*sN+w*u[N-1]
    return u

def SOR(A,u,w,f,N):
    u0 = u
    for i in range(N):
        u0 = SORit(A,u0,w,f)
    return u0

In [220]:
#For testing methods on SPD matrix
#Create random matrix and mupltiply with transpose to have SPD matrix:

msize = 3
M = np.random.rand(msize,msize)
A = np.matmul(M,M.transpose())
usol = np.random.rand(msize)
print("solution: ",usol)
f = np.matmul(A,usol)

u = GauSei(A,np.zeros(msize),f,400)
print(u)


solution:  [0.7456542  0.84196654 0.34091529]
[0. 0. 0.]
[1.74093763 1.79094738 0.23202435]
[0.32153036 1.46640094 1.0276776 ]
[-0.60637938  0.3534728   1.54782035]
[-0.66418362 -0.37408221  1.5802227 ]
[-0.26675422 -0.41940533  1.35744239]
[ 0.07603572 -0.10778908  1.1652904 ]
[0.15802556 0.16098548 1.11933074]
[0.05929291 0.22527203 1.17467563]
[-0.058173    0.14785779  1.24052152]
[-0.10416244  0.05575517  1.26630105]
[-0.08451932  0.0196958   1.25529004]
[-0.04697205  0.03509756  1.2342428 ]
[-0.02657935  0.06453761  1.2228116 ]
[-0.02834382  0.08052711  1.22380068]
[-0.03948488  0.07914362  1.23004584]
[-0.04747725  0.07040815  1.23452599]
[-0.04849333  0.06414149  1.23509555]
[-0.04548108  0.06334481  1.23340703]
[-0.04260688  0.06570664  1.23179588]
[-0.0417665   0.06796025  1.23132481]
[-0.04247308  0.06861918  1.23172088]
[-0.04343488  0.06806516  1.23226002]
[-0.04386008  0.06731103  1.23249837]
[-0.04373783  0.06697764  1.23242984]
[-0.04343775  0.0670735   1.23226163]
[-0.0

In [239]:
M = np.array([[16,4],[-1,10]])
b = np.array([3,10])
ugs = GauSei(M,[0,0],b,5)
usor = SOR(M,[0,0],0.5,b,100)

print("GS: ", ugs)
print("SOR: ", usor)


GS:  [-0.0625, 1.0]
SOR:  [-0.0625, 1.0]
